apiVersion: v1
kind: Service
metadata:
  name: remote-service
spec:
  ports:
  - name: remote-service
    port: {{ .Values.port | default 80 }}
    targetPort: {{ .Values.targetPort | default 80 }}
  type: ExternalName
  externalName: "{{ .Values.endpointDomain | required "endpointDomain is required for `local-test-proxy` chart" }}"
